import React from 'react'
import NavTopBar from '../layout/NavTopBar'
import Footer from '../layout/Footer'

const TermsOfUse = () => {

  const textWithQuotes = "  Schools may have their own policies that place restrictions on a student's ability to make commercial use of study materials, even otherwise lawful materials that the student has independently created. You are responsible for becoming familiar with such policies, abiding by them, and discontinuing the use of any Services if such use is contrary to your school policy or the instruction of your professor.";

  const textWithoutQuotes = textWithQuotes.replace(/"/g, '');





  return (
    <>
      <NavTopBar />
      <div>
        <section className="terms_privacy">
          <div className="container">
            <div className="row py-5 mt-5">
              <div className="col-12 text-center shadow policy p-5">
                <h1 className="display-5 fw-bold gray-900">Terms of Use - TeacherCool </h1>
                <p className="fs-5 gray-600 fw-normal text-center mb-5">
                  Teachercool reserves the right, in our sole discretion, to make changes to or discontinue any of the Services at any time. Any description of the Services provided by Teachercool is not a representation that the Services are working or will always work in that manner, as Teachercool is continuously updating the Services, and these updates may not always be reflected in the Terms of Use.
                </p>
                <h2 className='text-start fs-3'>Mobile Use </h2>
                <p className='terms-use'>

                  The Services may offer features and services that are available to you via your mobile device. These features and services may include, without limitation, the ability to upload content to the Services, receive messages from the Services, download applications to your mobile phone or access features from the Services (collectively, the Mobile Features). We may charge for Mobile Features and these charges will be disclosed prior to completion of registration for the Mobile Feature. Also, standard messaging, data and other fees may be charged by your carrier. Carrier fees and charges will appear on your mobile bill or be deducted from your pre-paid balance. Your carrier may prohibit or restrict certain Mobile Features and certain Mobile Features may be incompatible with your carrier or mobile device. Contact your carrier with questions regarding these issues.

                </p>

                <p className='terms-use'>

                  If you change or terminate your mobile account, you agree to promptly update your Teachercool account information so that any messages or notices from Teachercool regarding the Services are sent to you and not to the person who is assigned your old number.
                </p>
                <p className='terms-use'>
                  For any of our mobile apps, you agree that the third-party store or platform through which our apps are available (including, without limitation, the Apple App Store) is not liable to you in connection with our apps. If you use any ISBN scan feature of the Services, you are responsible for verifying the accuracy of the scanned code before relying on it.
                </p>



                <p className='terms-use'>

                  Notwithstanding any other provision within these Terms of Use, the following additional terms are applicable to those using any app governed by these Terms on an Apple iOS device (“App”): You understand that these Terms of Use are between you and Teachercool only, and not Apple, Inc. (“Apple”), and that Teachercool (or any third-party developer that may own and operate the App) are responsible for the App and the content thereof. You further understand that the App may not be used in any manner inconsistent with the Apple App Store Terms of Service as of the date hereof.
                </p>



                <p className='terms-use'>

                  You are granted a license to use the App on any iOS device that you own or control and as permitted by the “Usage Rules” set forth in the Apple App Store Terms of Service. We are solely responsible for providing maintenance and support for the sites, as specified in these terms or as required under applicable law. You understand that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the sites. We are solely responsible for any warranties, whether express or implied by law, to the extent not effectively disclaimed. In the event of any failure of the App to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the App to you (if any); and that, to the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the App, and any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be the sole responsibility of us. We, not Apple, are responsible for addressing any claims by you or any third-party relating to the App or your possession and/or use of the App, including, but not limited to: (i) product liability claims; (ii) any claim that the App fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation. Our liability is limited so far as permitted by applicable law. In the event of any third-party claim that the App or your possession and use of such App infringes that third-party’s intellectual property rights, we, not Apple, are solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim. You and we acknowledge and agree that Apple will have the right (and will be deemed to have accepted the right) to enforce the Terms against you as a third-party beneficiary thereof. You represent and warrant that you are not located in a country that is subject to a United States government embargo, or that has been designated by the United States government as a “terrorist supporting” country; and that you are not listed on any United States government list of prohibited or restricted parties. You must comply with all applicable third-party terms of agreement when using the application. If you have any questions or concerns regarding the App, please contact us as described in these Terms of Use.
                </p>


                <h2 className='text-start fs-3'>Email and Text Message Notifications </h2>
                <p className='terms-use'>
                  Notifications or receipts from Teachercool will be delivered to you by email at the address you provided to Teachercool when you created your account or as later updated. You may also opt to receive text message reminders from Teachercool as a courtesy to you. Please review our text message mobile disclosures, which are incorporated into the Terms of Use. Teachercool may contact you, sometimes through an automated or pre-recorded message, using the phone numbers you provide to Teachercool, including wireless numbers, to remind you that rental books are due to be returned or otherwise provide the Services.
                </p>

                <p className='terms-use'>

                  You are still responsible for compliance with the Terms of Use, including, e.g., timely return of your books, whether or not you receive such reminders via email, text or otherwise. Teachercool will not ask you for your personal information, account username, and password, or any information about you or your method of payment via email or text message. If you receive such an email or text message purportedly from Teachercool, it is fraudulent and Teachercool will have no responsibility for any misuse of any information you provide as a result.
                </p>

                <h2 className='text-start fs-3'>Account Cancellation</h2>
                <p className='terms-use'>
                  You may request cancellation of your account at any time throughout your use of our Services. To the fullest extent permissible under applicable law, your account will only be cancelled and closed after you have returned all books that have been rented to you (if any) and all transactions have been processed including payment of assessed penalties or the cashing of any refund check, if applicable. Teachercool may cancel your account in its sole discretion for any reason, including but not limited to inactivity or misuse. Even if your account is cancelled, your photos, bibliographic and citation information, comments, likes, friendships, and any other data you have shared via the Services may persist within the Service after cancellation of your account (for example, if your content has been reshared by others).
                </p>



                <h2 className='text-start fs-3'>Payments and Payment Processing</h2>
                <p className='terms-use'>
                  Validation: Teachercool may require users of the Services to provide a valid method of payment (e.g. credit or debit card, PayPal account, etc.) tied to an account at a financial institution when they register for an account (to ensure users are able to make applicable payments to Teachercool) or upon ordering products or services. If a method of payment is required, you are responsible for ensuring that a valid method of payment is associated with your Teachercool account at all times (either the original method of payment or a replacement). To confirm your method of payment is valid, Teachercool may initiate a pending charge on the account. This charge will not be confirmed and, therefore, you will not be charged, and it will simply disappear from your financial statement (usually within seven days - check with your financial institution for additional information). Please be aware that this pending charge may be initiated each time you edit the payment information for your account or place an order that cannot be processed.
                </p>

                <p className='terms-use'>

                  Authorization Holds: For certain transactions (e.g., book rentals), we may authorize anticipated charges and taxes from your method of payment. The amount of the authorization sought will depend on the transaction and may also vary depending on the nature of the payment method you have provided. This is sometimes referred to as an authorization hold and these funds may not be available for your use. If the fees incurred exceed the authorization hold (e.g., because of an auto-extension or unreturned, lost, stolen, or damaged book), we may automatically request additional authorization holds. If the provider for your method of payment rejects any authorization, you agree that we may charge any other method of payment we have on file for you (without notice to you, unless required by applicable law). At the conclusion or termination of an ongoing transaction (e.g., return of a rented book), if the charges do not exceed the amount due, the authorization for the amount not utilized will be released per the rules of your payment method provider. The timeframe for an authorization hold to be removed will depend on the policies of your financial institution. You are responsible and liable for ensuring that enough funds are available in connection with the payment method used at the time any transaction is processed.
                </p>

                <p className='terms-use'>

                  Other Policies: Where your billing address is requested you must provide the address and phone number your financial institution has on record, as well as the cards security code (e.g. CVC CVV CID). Teachercool will make reasonable efforts to process your transactions in a timely manner but we make no guarantees regarding the processing time for charges. Teachercool may store your method of payment and you hereby acknowledge and agree that Teachercool may charge you for and you will pay for, any charges specified on the Services and for any auto-extension or unreturned lost stolen or damaged books associated with your account under the terms of your book rental and in accordance with the General Policies. For any books or other materials kept beyond the applicable rental term, you agree to be charged the applicable late fees as set out in our General Policies. For any books or other rental materials that are never returned (an item is deemed never returned if it has not been returned in the period posted in our General Polices) or that are returned damaged you agree to be charged for the value of the item(s) as set out in our General Policies. Teachercool reserves the right to place you into collections if you fail to timely pay for the products and services ordered through the Services collections may be done by Teachercool or a third-party on Teachercools behalf. You also agree that we may at our discretion send your account to a collection agency and except where prohibited by local law recover our reasonable costs of collection from you if you fail to pay all fees due and owing to Teachercool. For security reasons or to otherwise confirm a financial instrument or payment Teachercool may delay mailings of books or otherwise delay providing payments or services even if such delay impacts a guaranteed delivery date.
                </p>



                <h2 className='text-start fs-3'>Third-Party Links, Content and Applications</h2>
                <p className='terms-use'>
                  There may be links from the Services, or from communications you receive from the Services, to third-party websites or online features. The Services also may include third-party content that we do not control, maintain, or endorse.
                </p>
                <p className='terms-use'>

                  Functionality on the Services may also permit interactions between the Services and a third-party website or online feature including applications that connect the Services or your profile on the Services with a third-party site. For example the Services may include a button enabling you to indicate on your social networking page that you like a specific product on the Services, or a feature that lets you post to your social networking page a link to a specific product or the ability to share content from the Services or your User Content with a third-party which may be publicly posted on that third-partys website. Using this functionality typically requires you to login to your account on the third-party website. We do not control any of these third-party sites or any of their content. Neither Teachercool nor its service providers are responsible for the practices of any third-party. Accordingly you expressly acknowledge and agree that we make no representations or warranties about the completeness accuracy or existence of any advertising products or other materials on or available from third-party sites or online features and any reliance placed by you on such materials is at your own risk. YOUR CORRESPONDENCE AND BUSINESS DEALINGS WITH SUCH THIRD-PARTIES FOUND THROUGH THE SERVICES INCLUDING, WITHOUT LIMITATION THE PAYMENT AND DELIVERY OF PRODUCTS AND SERVICES AND ANY TERMS CONDITIONS WARRANTIES AND REPRESENTATIONS ASSOCIATED WITH ANY SUCH DEALINGS ARE SOLELY BETWEEN YOU AND THE THIRD-PARTY.
                </p>


                <h2 className='text-start fs-3'>Linking Policy</h2>
                <p className='terms-use'>
                  Teachercool grants you the revocable permission to link to the websites on which these Terms of Use are posted; provided, however, that any link to such a website: (a) must not frame or create a browser or border environment around any of the content on such websites or otherwise mirror any part of such websites; (b) must not imply that Teachercool or the Services are endorsing or sponsoring any third-party or its products or services, unless Teachercool has given the third-party prior written consent; (c) must not present false, misleading or offensive information about Teachercool or its products or services; (d) must not use any Teachercool trademarks without the prior written permission from Teachercool; (e) must not contain content that could be construed as distasteful, offensive or controversial or otherwise objectionable; and (f) must be owned and controlled by you or the person or entity placing the link, or otherwise permit you to enable such link subject to these Terms of Use. By linking to a Teachercool Website, you agree that you do and will continue to comply with the above linking requirements.
                </p>

                <p className='terms-use'>

                  Notwithstanding anything to the contrary contained in these Terms of Use, Teachercool reserves the right to prohibit linking to any Teachercool Website for any reason in our sole and absolute discretion.
                  Course Searches and Other Information Specific to an Academic Institution

                </p>
                <p className='terms-use'>
                  We may tie your Teachercool experience to information about the school you have identified to Teachercool. For certain schools, the Services enable you to search and retrieve information about the materials required for particular courses. Please be aware that course information and assigned materials may change from time to time, and Teachercool may not receive updated information from the school in a timely manner. Teachercool is not responsible for any errors in the information provided in the course searches on the Services. Where specific school names or information relate to a specific school are displayed, they do not imply any endorsement or approval by the school. Except where specifically stated, Teachercool has no affiliation with nor endorsement from any academic institution, and school names and information are used on the Services only to the extent necessary to organize, identify and permit use of information and sections of the Services that may be tailored to students of a particular school, or for other lawful uses.
                </p>

                <h2 className='text-start fs-3'>Categories of Users</h2>
                <p className='terms-use'>
                  You may use Teachercools homework help services as a Member or a Visitor. Members may include a variety of designated levels of members who may be charged for services according to the terms of the particular offer or registered free members (a Free Member) or other membership levels.
                </p>
                <p className='terms-use'>
                  Visitors are users that have not registered for an account with access to and use of certain aspects of the homework help services, which may be restricted and only available to certain Members. The membership levels, the benefits and pricing of each level of membership may vary and are subject to change at any time, please read the terms of any particular level of membership carefully before accepting it. Teachercool may modify these levels and benefits from time to time, and each such modification is effective as soon as we post it on the relevant Services except to the extent that your particular pricing structure is established in writing for a period of time in the future, such as an annual plan. It is therefore important that you review the membership page regularly to ensure you are aware of any such changes.
                </p>

                <h2 className='text-start fs-3'>Homework Help, Study Guide and Note Usage</h2>
                <p className='terms-use'>
                  Teachercools homework help, study and note services are available merely as informational and study aids and should not be considered substitutes for applicable coursework homework class and lecture requirements assignment and related materials. In using the Services, you specifically agree not to use claim or submit as your own any portion of the help materials. Teachercool does not guarantee the accuracy or quality of answers or other study material that appear on the Services some of which may be posted by other users. You further agree the Services may present information that is incorrect or inconsistent when compared to similar content and materials, including solutions and their methodologies, provided or preferred by publishers of applicable problems or instructors of applicable courses.
                </p>


                <h2 className='text-start fs-3'>Outlines, Study Guides and Notes</h2>
                <p className='terms-use'>
                  Teachercool may permit users to upload and in some cases sell content for the purpose of aiding others in the education and learning process. Users may not post content owned or created (except if it is in the public domain) by another person and hereby represent and warrant that: (i) each was created by the user and the user is the sole owner of all content posted to Services sites and all rights in such content (except for public domain content), including, without limitation, copyright and (ii) the posting of Content on or through the Services will not breach the privacy rights, publicity rights, copyrights, contract rights, intellectual property rights or any other rights of any third-party. Users agree to pay for all royalties, fees, and any other monies owing to any third-party for any content provided by you to the Services. Users of the Services agree to exclude from such content any documents, records or files made accessible to them by (a) your school, professor or other instructor, (b) any board of examination, (c) any author or publisher whose works have been used as part of studies or (d) any co-student.
                </p>

                <p className='terms-use'>


                  In creating study related content, students must respect any intellectual property rights that others may have in content. All content posted on the Services must be independently created, transformative and non-derivative. It should not be a transcript or recording of anothers independent efforts, nor should it copy from materials purchased from or created by others. It should go beyond simply summarizing material covered in class or in written or recorded materials, but include information raised by students in or outside of class, and independent thought, analysis, and commentary. Class notes, for example, must be substantially rewritten after class and include independent thought and analysis, research and information; notes that use a lecturers words or that are not carefully reviewed, rethought and rewritten after class are not useful to or appreciated by students, and not permitted on the Services.

                </p>

                <p className='terms-use'>

                  {textWithoutQuotes}
                </p>
                <p className='terms-use'>
                  Class notes and study guides are solely for the specific use of students in the designated class for which they are created. Individuals who are not registered for a class may not purchase study guides, class notes or outlines for that class. Check the accuracy of all information from study guides, class notes, answers, and outlines – to the fullest extent permitted under applicable law, Teachercool does not guarantee their accuracy or completeness, they are simply an aid to the study process.
                </p>

                <h2 className='text-start fs-3'>Career Information and Jobs</h2>
                <p className='terms-use'>
                  Teachercools site may help students identify potential careers by providing a basic description for a variety of potential jobs. In some cases, Teachercool may provide salary ranges for jobs, and point users to potential job opportunities in that field, based upon your interests and skills that you have represented to Teachercool that you possess. Teachercool may also help identify skills that are commonly required for those jobs and recommend learning materials that (combined with your own efforts) may help you achieve better proficiency with those skills. Teachercools attempts to assess your skills, identify gaps, and match those gaps to available learning materials may not be accurate in your particular circumstances. Teachercool is simply one starting point, not an exhaustive list of all potential jobs or opportunities that might be available to you, and in a fast-changing employment landscape Teachercool does not guarantee that the descriptions, salaries and job opportunities set out on our site are always up to date, reflect the current job market, or are applicable to the market in your area. We believe that the materials on our site, if you use them and apply yourself, can improve your skills and employability. Still, Teachercool does not provide in-depth, individualized job counseling, and your success in landing a job in a particular career depends on a wide variety of factors. Our systems efforts to identify skills gaps, and recommend learning materials to address those gaps, may not result in improved employment prospects; completing recommended classes is not a guarantee of finding employment in that field or any other field.
                </p>

                <p className='terms-use'>


                  Teachercool may also help students or alumni find internships or entry level jobs or other positions by accepting postings of job descriptions from third-party employers, through its Internships.com website or other Teachercool Websites. Teachercool does not confirm the accuracy of the postings, nor can Teachercool know whether a particular position has been filled. Teachercool may recommend particular job postings to particular users based upon available data about the position or the user, or other criteria, but the actual criteria for job positions lie within the discretion of the employer and Teachercool makes no representations about the suitability of any candidate for any listed position.

                </p>

                <h2 className='text-start fs-3'>Learning Courses</h2>
                <p className='terms-use'>
                  Teachercool may offer third-party learning videos and instructional material. Teachercool does not hire or employ Instructors. We are not responsible for the content of such third-party materials, nor the advice provided in such materials. We do not control such materials and, as such, to the fullest extent permitted under applicable law, do not guarantee their reliability, validity, accuracy, or truthfulness. Completing such courses may provide you with skills and experience that may help your career prospects, but as noted above, there are a large number of factors tied to your career and completing such courses is no guarantee of improved employability or enhanced career prospects.
                </p>

                <p className='terms-use'>


                  Teachercool may also help students or alumni find internships or entry level jobs or other positions by accepting postings of job descriptions from third-party employers through its Internships.com website or other Teachercool Websites. Teachercool does not confirm the accuracy of the postings, nor can Teachercool know whether a particular position has been filled. Teachercool may recommend particular job postings to particular users based upon available data about the position or the user, or other criteria, but the actual criteria for job positions lie within the discretion of the employer and Teachercool makes no representations about the suitability of any candidate for any listed position.

                </p>

                <h2 className='text-start fs-3'>Test Prep Services</h2>
                <p className='terms-use'>
                  Teachercool may offer services to help students prepare for a variety of standardized tests. Any test prep courses branded as Teachercools and offered through the Teachercool Websites are copyrighted and the property of Teachercool, Inc., and are for the sole personal non-commercial use of individuals who register with Teachercool and pay for such services, subject to these Terms of Use. Teachercool test prep services are not endorsed nor affiliated with the companies who offer the test itself.
                </p>
                <h2 className='text-start fs-3'>Bibliography and Citation Services</h2>
                <p className='terms-use'>
                  Teachercool may offer citation, bibliography and plagiarism checker services, including but not limited to, EasyBib, BibMe, Cite This For Me, Citation Machine, Normas APA and other writing tools through the Teachercool Websites to help students and their educators develop student reading and writing skills. To the fullest extent permitted under applicable law, Teachercool does not guarantee the accuracy or quality of content that appears on the Services in connection with such citation, bibliography and plagiarism checker services and other writing tools.
                </p>
                <h2 className='text-start fs-3'>Disclaimer of Warranties</h2>
                <p className='terms-use'>
                  TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE Teachercool WEBSITES AND SERVICES ARE PROVIDED ON AN AS IS,AS AVAILABLE, AND WITH ALL FAULTS BASIS AND WITHOUT WARRANTIES, GUARANTEES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, Teachercool AND ITS SUBSIDIARIES, DIRECTORS, EMPLOYEES, MANAGERS, OFFICERS, AGENTS, REPRESENTATIVES, VENDORS, THIRD-PARTY DISTRIBUTORS AND THIRD-PARTY LICENSORS OF CONTENT SOLD THROUGH Teachercool (COLLECTIVELY THE Teachercool PARTIES) SPECIFICALLY MAKE NO REPRESENTATIONS, WARRANTIES, OR ENDORSEMENTS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, AS TO (A) THE Teachercool WEBSITES OR THE SERVICES; (B) THE Teachercool CONTENT; (C) USER CONTENT; AND/OR (D) SECURITY ASSOCIATED WITH THE TRANSMISSION OF INFORMATION TO Teachercool OR VIA THE SERVICES. IN ADDITION, TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, THE Teachercool PARTIES DISCLAIM ALL GUARANTEES, CONDITIONS, WARRANTIES OR CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, OF MERCHANTABILITY, NON-INFRINGEMENT, TITLE, CUSTOM, TRADE, QUIET ENJOYMENT, SYSTEM INTEGRATION, AND THE SERVICES WILL BE SECURE, TIMELY, UNINTERRUPTED, OR ERROR-FREE OR OPERATE IN COMBINATION WITH ANY OTHER HARDWARE, SOFTWARE, SYSTEM, OR DATA.
                </p>
                <p className='terms-use'>
                  TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE Teachercool PARTIES SPECIFICALLY DO NOT WARRANT THAT THE SERVICES WILL BE ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SERVICES OR THE SERVER, NETWORK OR OTHER SOFTWARE AND EQUIPMENT THAT MAKES THEM AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, Teachercool DOES NOT MAKE ANY REPRESENTATIONS OR WARRANTIES REGARDING THE CONTENT OF ITS PRODUCTS, WEBSITES OR SERVICES, OR REGARDING THE RESULTS OF THE USE OF THE SERVICES IN TERMS OF THEIR COMPLETENESS, CORRECTNESS, ACCURACY, RELIABILITY, USEFULNESS OR OTHERWISE, UNLESS SPECIFICALLY SET OUT ON THE SERVICES. YOU ACKNOWLEDGE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE Teachercool PARTIES DO NOT WARRANT THAT YOUR USE OF THE SERVICES IS LAWFUL IN ANY PARTICULAR JURISDICTION, AND THE Teachercool PARTIES SPECIFICALLY DISCLAIM SUCH WARRANTIES. BY ACCESSING OR USING THE SERVICES YOU REPRESENT AND WARRANT THAT YOUR ACTIVITIES ARE LAWFUL IN EVERY JURISDICTION WHERE YOU ACCESS OR USE THE SERVICES.
                </p>
                <p className='terms-use'>
                  TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE Teachercool PARTIES SPECIFICALLY DO NOT WARRANT THAT THE SERVICES WILL BE ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SERVICES OR THE SERVER, NETWORK OR OTHER SOFTWARE AND EQUIPMENT THAT MAKES THEM AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, Teachercool DOES NOT MAKE ANY REPRESENTATIONS OR WARRANTIES REGARDING THE CONTENT OF ITS PRODUCTS, WEBSITES OR SERVICES, OR REGARDING THE RESULTS OF THE USE OF THE SERVICES IN TERMS OF THEIR COMPLETENESS, CORRECTNESS, ACCURACY, RELIABILITY, USEFULNESS OR OTHERWISE, UNLESS SPECIFICALLY SET OUT ON THE SERVICES. YOU ACKNOWLEDGE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE Teachercool PARTIES DO NOT WARRANT THAT YOUR USE OF THE SERVICES IS LAWFUL IN ANY PARTICULAR JURISDICTION, AND THE Teachercool PARTIES SPECIFICALLY DISCLAIM SUCH WARRANTIES. BY ACCESSING OR USING THE SERVICES YOU REPRESENT AND WARRANT THAT YOUR ACTIVITIES ARE LAWFUL IN EVERY JURISDICTION WHERE YOU ACCESS OR USE THE SERVICES.
                </p>



                <p className='terms-use'>THE Teachercool PARTIES ARE NOT RESPONSIBLE FOR THE USER CONTENT, ACCURACY OR OPINIONS EXPRESSED IN USER CONTENT POSTED OR PROVIDED BY THIRD-PARTIES ON THE SERVICES OR LINKED SERVICES, AND SUCH SERVICES ARE NOT NECESSARILY INVESTIGATED, MONITORED OR CHECKED FOR ACCURACY OR COMPLETENESS BY Teachercool. INCLUSION OF ANY LINKED WEBSITE OR FEATURE ON THE SERVICES DOES NOT IMPLY APPROVAL OR ENDORSEMENT OF THE LINKED WEBSITE OR FEATURE BY Teachercool. POSTS AND LINKED SERVICES CREATED AND POSTED BY USERS ON, THOUGH OR IN CONNECTION WITH THE SERVICES MAY CONTAIN LINKS TO OTHER WEBSITES OR SERVICES. Teachercool TAKES NO RESPONSIBILITY FOR THIRD-PARTY ADVERTISEMENTS OR LINKED SERVICES THAT ARE POSTED ON, THROUGH OR IN CONNECTION WITH THE SERVICES OR LINKED SERVICES, NOR DOES IT TAKE ANY RESPONSIBILITY FOR THE GOODS OR SERVICES PROVIDED BY THESE THIRD-PARTIES. THIS DISCLAIMERS SECTION SHALL SURVIVE ANY EXPIRATION OR TERMINATION OF YOUR RELATIONSHIP WITH Teachercool.</p>

                <p className='terms-use'>
                  SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF GUARANTEES, CONDITIONS, WARRANTIES OR TERMS IMPLIED OR IMPOSED BY ANY APPLICABLE LAW. NOTHING IN THIS AGREEMENT EXCLUDES, RESTRICTS OR MODIFIES ANY GUARANTEE, WARRANTY, TERM OR CONDITION, RIGHT OR REMEDY IMPLIED OR IMPOSED BY ANY APPLICABLE LAW WHICH CANNOT LAWFULLY BE EXCLUDED, RESTRICTED OR MODIFIED.
                </p>

                <h2 className='text-start fs-3'>Limitations of Liability; Waiver</h2>
                <p className='terms-use'>

                  TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, ‎IN NO EVENT SHALL THE Teachercool PARTIES BE LIABLE FOR ANY INDIRECT, ECONOMIC, SPECIAL, INCIDENTAL OR CONSEQUENTIAL LOSSES OR DAMAGES RELATED TO: (A) THE SERVICES; (B) THE Teachercool CONTENT; (C) USER CONTENT; (D) YOUR USE OF, INABILITY TO USE, OR THE PERFORMANCE OF THE SITE; (E) ACTION TAKEN IN CONNECTION WITH AN INVESTIGATION BY THE Teachercool PARTIES OR LAW ENFORCEMENT AUTHORITIES REGARDING YOUR USE OF THE SITE; (F) ACTION TAKEN IN CONNECTION WITH COPYRIGHT OR OTHER INTELLECTUAL PROPERTY OWNERS; (G) ANY ERRORS OR OMISSIONS IN THE SERVICES TECHNICAL OPERATION; OR (H) ANY DAMAGE THAT RESULTS FROM EVENTS BEYOND OUR REASONABLE CONTROL, SUCH AS DAMAGES TO ANY USERS COMPUTER, MOBILE DEVICE, OR OTHER EQUIPMENT OR TECHNOLOGY INCLUDING, WITHOUT LIMITATION, DAMAGE FROM ANY SECURITY BREACH OR FROM ANY VIRUS, BUGS, TAMPERING, FRAUD, ERROR, OMISSION, INTERRUPTION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER LINE OR NETWORK FAILURE OR ANY OTHER TECHNICAL OR OTHER MALFUNCTION, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOST PROFITS, LOSS OF GOODWILL, LOSS OF DATA, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, EVEN IF FORESEEABLE OR EVEN IF THE Teachercool PARTIES HAVE BEEN ADVISED OF OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL THE Teachercool PARTIES TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES OR CAUSES OR ACTION EXCEED THE AMOUNTS PAID BY YOU, IF ANY, TO Teachercool IN THE PAST SIX MONTHS, OR $250, WHICHEVER IS GREATER. THE PRIOR LIMITATION ON DAMAGES IS NOT INTENDED TO LIMIT THE Teachercool PARTIES OBLIGATION TO PAY PREVAILING PARTY COSTS OR FEES TO THE STRICT EXTENT RECOVERABLE PURSUANT TO APPLICABLE LAW. THE LIMITATIONS SET FORTH IN THIS SECTION WILL NOT LIMIT OR EXCLUDE THE Teachercool PARTIES LIABILITY FOR PERSONAL INJURY OR PROPERTY DAMAGE CAUSED BY THE Teachercool PARTIES, OR FOR THE Teachercool PARTIES GROSS NEGLIGENCE, FRAUD OR INTENTIONAL, WILLFUL, MALICIOUS OR RECKLESS MISCONDUCT, OR FOR LOSSES OR DAMAGES WHICH CANNOT BE LAWFULLY EXCLUDED OR LIMITED BY APPLICABLE LAWS IN YOUR JURISDICTION. THIS SECTION SHALL SURVIVE ANY EXPIRATION OR TERMINATION OF YOUR RELATIONSHIP WITH Teachercool.
                </p>
                <p className='terms-use'>YOU AGREE THAT IN THE EVENT YOU INCUR ANY DAMAGES, LOSSES OR INJURIES THAT ARISE OUT OF THE Teachercool PARTIES ACTS OR OMISSIONS, THE DAMAGES, IF ANY, CAUSED TO YOU ARE NOT IRREPARABLE OR SUFFICIENT TO ENTITLE YOU TO AN INJUNCTION PREVENTING ANY EXPLOITATION OF ANY WEBSITE, PROPERTY, PRODUCT, SERVICE, OR OTHER Teachercool CONTENT OWNED OR CONTROLLED BY THE Teachercool PARTIES, AND YOU WILL HAVE NO RIGHTS TO ENJOIN OR RESTRAIN THE DEVELOPMENT, PRODUCTION, DISTRIBUTION, ADVERTISING, EXHIBITION OR EXPLOITATION OF ANY WEBSITE, PROPERTY, PRODUCT, SERVICE, OR OTHER Teachercool CONTENT OWNED OR CONTROLLED BY THE Teachercool PARTIES.</p>
                <p className='terms-use'>BY ACCESSING THE SERVICES, YOU UNDERSTAND THAT YOU MAY BE WAIVING RIGHTS WITH RESPECT TO CLAIMS THAT ARE AT THIS TIME UNKNOWN OR UNSUSPECTED, AND IN ACCORDANCE WITH SUCH WAIVER, YOU ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTAND, AND HEREBY EXPRESSLY WAIVE, THE BENEFITS OF SECTION 1542 OF THE CIVIL CODE OF CALIFORNIA, AND ANY SIMILAR LAW OF ANY STATE, PROVINCE, OR TERRITORY, WHICH PROVIDES AS FOLLOWS: A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR.</p>
                <h2 className='text-start fs-3'>Indemnity</h2>
                <p className='terms-use'>
                  To the fullest extent permitted by applicable law, you agree to defend, indemnify and hold harmless the Teachercool Parties from and against any and all loss, liability, damages, judgments, claims, demands, costs, investigations, settlements, and expenses (including, without limitation, reasonable attorneys fees) arising out of or directly or indirectly relating to (a) your User Content; (b) your breach or anticipatory breach of these Terms of Use; (c) your violation of any laws, rules, regulations, codes, statutes, ordinances or orders of any governmental and quasi-governmental authorities, including, without limitation, all regulatory, administrative and legislative authorities; (d) information or material transmitted through your computer, even if not submitted by you, that infringes, violates or misappropriates any copyright, trademark, trade secret, trade dress, patent, publicity, privacy or other right of any person or defames any person; (e) any misrepresentation made by you; or (f) the Teachercool Parties use of your information or User Content as permitted under these Terms of Use, the Privacy Policy, or any other written agreement between you and Teachercool. You will cooperate as fully required by the Teachercool Parties in the defense of any claim. The Teachercool Parties reserve the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and you will not in any event settle any claim without the prior written consent of a duly authorized employee of the Teachercool Parties. These indemnity obligations shall survive any expiration or termination of your relationship with Teachercool.
                </p>
                <h2 className='text-start fs-3'>Export</h2>
                <p className='terms-use'>
                  Software related to or made available by the Services may be subject to the export control laws of the United States or any other relevant jurisdiction which requires any export license or other governmental approval prior to exporting such materials, product, or content. In particular, but without limitation, no software from the Services may be downloaded, exported or re-exported: (a) into (or to a national or resident of) Cuba, North Korea, Iran, Syria or any other country to which the United States has embargoed goods; (b) to anyone on the United States Treasury Departments list of Specially Designated Nationals or the United States Commerce Departments Table of Deny Orders; or (c) to any other party that may be subject to any export controls or embargo restrictions applicable in your jurisdiction. By downloading any software related to Teachercool Websites, you represent and warrant that you are not located in, under the control of, or a national or resident of, any such country or on any such list. Further, by using any of the Services, you represent and warrant that you are not on any United States or other government list of restricted or prohibited persons with whom a United States company or a company offering business in your jurisdiction may do business.
                </p>
                <h2 className='text-start fs-3'>Reporting Copyright and Other Intellectual Property Violations</h2>
                <p className='terms-use'>
                  Teachercool respects the intellectual property rights of others and takes the protection of copyrights and other intellectual property seriously. Only the intellectual property rights owner or person authorized to act on behalf of the owner can report potentially infringing content. If you believe your work has been infringed through the Services, please notify us at Teachercool, Inc., Attention: Copyright Agent, 3990 Freedom Circle, Santa Clara, CA 95054, 408-855-5700, CopyrightAgent@Teachercool.com.

                </p>
                <p className='terms-use'>Your contact information, including name, address, telephone number, and email address;</p>
                <p className='terms-use'>A description of the copyrighted work you claim has been infringed (including, e.g., the title, ISBN and other bibliographic information for books);</p>
                <p className='terms-use'>A reasonably specific description of where the allegedly infringing material is located on the Services (including, e.g., the URL);</p>
                <p className='terms-use'>A statement by you that you have a good-faith belief that the allegedly infringing material is not authorized by the copyright owner, its agent, or the law;</p>
                <p className='terms-use'>Your electronic or physical signature;</p>
                <p className='terms-use'>A statement by you, made under penalty of perjury, that the information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owners behalf; and</p>
                <p className='terms-use'>Information reasonably sufficient to permit us to contact the complaining party.</p>
                <p className='terms-use'>NOTE: This contact information is for inquiries regarding potential copyright and other infringement only.</p>
                <p className='terms-use'>It is often difficult to determine if your intellectual property rights have been violated or if the DMCA requirements have been met. We may request additional information before we remove any infringing material. If a dispute develops as to the correct owner of the rights in question, we reserve the right to remove your content along with that of the alleged infringer pending resolution of the matter.</p>
                <p className='terms-use'>Teachercool will provide you with notice if your materials have been removed based on a third-party complaint of alleged infringement of the third-partys intellectual property rights.</p>
                <p className='terms-use'>
                  IF YOU KNOWINGLY MISREPRESENT THAT MATERIAL IS OR IS NOT INFRINGING, YOU MAY BE SUBJECT TO CIVIL PENALTIES. THESE INCLUDE MONETARY DAMAGES, COURT COSTS, AND ATTORNEYS FEES INCURRED BY Teachercool, BY ANY COPYRIGHT OWNER, OR BY ANY COPYRIGHT OWNERS LICENSEE THAT IS INJURED AS A RESULT OF RELIANCE UPON YOUR MISREPRESENTATION. YOU MAY ALSO BE SUBJECT TO CRIMINAL PROSECUTION FOR PERJURY. You agree we may provide your notice to the provider of the allegedly infringing material.
                </p>
                <h2 className='text-start fs-3'>Informal Dispute Resolution</h2>
                <p className='terms-use'>
                  There might be instances when a Dispute (as defined under Dispute Resolution below) arises between you and Teachercool. If that occurs, Teachercool is committed to working with you to reach a reasonable resolution. You and Teachercool agree that good faith informal efforts to resolve Disputes can result in a prompt, low-cost and mutually beneficial outcome. Except to the extent prohibited by applicable consumer protection law, you and Teachercool therefore agree that before either party commences arbitration or against the other (or initiates an action in small claims court if a party so elects), we will personally meet and confer telephonically or via videoconference, in a good faith effort to resolve informally any Dispute covered by this Arbitration Agreement (Informal Dispute Resolution Conference). If you are represented by counsel, your counsel may participate in the conference, but you will also participate in the conference.
                </p>
                <p className='terms-use'>The party initiating a Dispute must give notice to the other party in writing of his or her intent to initiate an Informal Dispute Resolution Conference, which shall occur within 45 days after the other party receives such notice, unless an extension is mutually agreed upon by the parties. Notice to Teachercool that you intend to initiate an Informal Dispute Resolution Conference should be sent by email to legal or regular mail to our offices located at Teachercool, Inc., 3990 Freedom Circle, Santa Clara, CA 95054, Attn: General Counsel. The notice must include: (1) your name, telephone number, mailing address, email address associated with your account and your account username; (2) the name, telephone number, mailing address and email address of your counsel, if any; and (3) a description of your claim.</p>
                <p className='terms-use'>The Informal Dispute Resolution Conference shall be individualized such that a separate conference must be held each time either party initiates a claim, even if the same law firm or group of law firms represents multiple users in similar cases, unless all parties agree otherwise; multiple individuals initiating a Dispute cannot participate in the same Informal Dispute Resolution Conference unless all parties agree otherwise. In the time between a party receiving notice and the Informal Dispute Resolution Conference, nothing in this Arbitration Agreement shall prohibit the parties from engaging in informal communications to resolve the initiating partys claims. Engaging in the Informal Dispute Resolution Conference is a condition precedent and requirement that must be fulfilled before commencing arbitration. The statute of limitations and any filing fee deadlines shall be tolled while the parties engage in the Informal Dispute Resolution Conference process required by this section.</p>
                <p className='terms-use'>TTHE FOLLOWING DISPUTE RESOLUTION, CLASS ACTION WAIVER, AND ARBITRATION PROVISIONS WILL NOT APPLY TO THE EXTENT PROHIBITED UNDER CONSUMER PROTECTION LAWS IN QUEBEC, OR IN ANY OTHER PROVINCE OR TERRITORY IN CANADA, AND ARE INTENDED TO ONLY APPLY TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW. TO THE EXTENT THE BELOW DISPUTE RESOLUTION, CLASS ACTION WAIVER, AND ARBITRATION PROVISIONS DO NOT APPLY TO YOU BECAUSE THEY ARE PROHIBITED UNDER CONSUMER PROTECTION LAWS IN QUEBEC OR ANY OTHER PROVINCE OR TERRITORY IN CANADA, YOU AND WE AGREE THAT ANY DISPUTE, CLAIM OR CONTROVERSY BETWEEN US ARISING OUT OF OR RELATED TO THE TERMS OF USE OR THE BREACH, TERMINATION, ENFORCEMENT, INTERPRETATION OR VALIDITY THEREOF, OF THE SERVICES OR YOUR USE OF THE SERVICES (CANADIAN DISPUTES) SHALL BE CONSTRUED AND EVALUATED ACCORDING TO THE LAWS OF YOUR PROVINCE OR TERRITORY OF RESIDENCE, AND THE FEDERAL LAWS OF CANADA APPLICABLE THEREIN, WITHOUT REFERENCE TO ANY CONFLICTS OF LAWS PRINCIPLES. YOU HEREBY IRREVOCABLY SUBMIT TO THE EXCLUSIVE JURISDICTION OF THE CONSUMER PROTECTION TRIBUNALS OR COURTS IN YOUR PROVINCE OR TERRITORY OF RESIDENCE AS THE PROPER AND MOST CONVENIENT FORUM FOR ANY CANADIAN DISPUTES.</p>
                <h2 className='text-start fs-3'>Dispute Resolution</h2>
                <p className='terms-use'>
                  If a dispute arises between you and Teachercool, our goal is to provide you with a neutral and cost-effective means of resolving the dispute quickly. Accordingly, you and Teachercool agree that any dispute, claim or controversy between us arising out of or related to the Terms of Use or the breach, termination, enforcement, interpretation or validity thereof, of the Services or your use of the Services (collectively, Disputes) will be finally settled by individual binding arbitration in accordance with this Dispute Resolution section, and not in a court of law. This Dispute Resolution section shall also be referred to as the Arbitration Agreement. Notwithstanding the foregoing, either party retains the right to bring an individual action in small claims court, if the claims qualify, so long as the matter remains in such court and advances only on an individual (non-class, non-representative) basis.
                </p>
                <p className='terms-use'>Without limiting the preceding sentence, you will also have the right to litigate Disputes in a court of competent jurisdiction if you provide Teachercool with written notice of your desire to do so by email to legal or regular mail at our offices located at Teachercool, Inc., 3990 Freedom Circle, Santa Clara, CA 95054, Attn: General Counsel within thirty (30) days following the date you first receive these Terms of Use (Arbitration Opt-out Notice). Such notice must include your full name, address, Teachercool username, the email address you currently use to access your Teachercool account, and a clear statement that you want to opt out of this Arbitration Agreement. If you do not provide Teachercool with an Arbitration Opt-out Notice within this thirty (30) day period, you will be deemed to have knowingly and intentionally waived your right to litigate any Dispute in court except as expressly set forth with respect to individual actions in small claims courts.</p>
                <p className='terms-use'>You acknowledge and agree that you and Teachercool are each waiving the right to a trial by jury or to participate as a plaintiff or class member in any purported class action or representative proceeding.</p>
                <p className='terms-use'>An arbitrator can award on an individual basis the same damages and relief as a court and must follow these Terms of Use as a court would. However, there is no judge or jury in arbitration, and court review of an arbitration award is subject to very limited review. Notwithstanding the foregoing, each party reserves the right to seek injunctive or other equitable relief in a court of competent jurisdiction with respect to any dispute related to the actual or threatened infringement, misappropriation or violation of a partys intellectual property or proprietary rights or breach of the User Content and Activities provisions of this Agreement.</p>
                <h2 className='text-start fs-3'>Class Action Waiver</h2>
                <p className='terms-use'>
                  To the fullest extent permitted by applicable law, you and Teachercool agree to waive the right to have any Dispute within the scope of this Arbitration Agreement be brought, heard, administered, resolved, or arbitrated on a class, collective, or mass action basis, and as such all disputes within the scope of this Arbitration Agreement must be arbitrated on an individual basis and not on a class, collective or mass basis, and an arbitrator shall not have any authority to hear, arbitrate or resolve any claim on a class, collective, and/or mass action basis, or to award relief to anyone but the individual in arbitration (Class Action Waiver), or to consolidate arbitrations, except as provided in the Batch Arbitration section below. If, however, this Class Action Waiver is deemed invalid or unenforceable with respect to a particular Dispute, or if the Class Action Waiver is not permitted in your jurisdiction of residence, neither you nor Teachercool will be entitled to arbitration of such Dispute. If a court determines by means of a final decision not subject to any further appeal or recourse, that the Class Action Waiver is invalid or unenforceable with respect to a particular claim or request for relief, or if the Class Action Waiver is not permitted in your jurisdiction of residence, you and Teachercool agree that that particular claim or request for relief may be adjudicated in court, but shall be severed and the court proceeding stayed pending arbitration of the remaining claims. This Class Action Waiver does not prevent you or Teachercool from participating in a class-wide settlement of claims.
                </p>
                <h2 className='text-start fs-3'>Commencing the Arbitration, Arbitration Rules, Governing Law</h2>
                <p className='terms-use'>
                  If the Informal Dispute Resolution Conference process above does not resolve satisfactorily the Dispute within 60 days after receipt of the notice, you and Teachercool agree that either party shall seek to finally resolve the Dispute through binding individual arbitration. The arbitration will be administered by the American Arbitration Association (AAA) in accordance with the Consumer Arbitration Rules (the AAA Rules) then in effect, except as modified by this section of these Terms of Use. (The AAA Rules are available at www.adr.org.)
                </p>
                <p className='terms-use'>A party who desires to initiate arbitration must provide the other party with a Request for Arbitration (the Request). The Request must include: (1) the name, telephone number, mailing address, email address of the party seeking arbitration and the account username as well as the email address associated with the account; (2) a statement of the legal claims being asserted and the factual bases of those claims; (3) a description of the remedy sought and an accurate, good-faith calculation of the amount in controversy in United States dollars; (4) a statement certifying completion of the Informal Dispute Resolution Conference as described above; and (5) the partys portion of the applicable filing fee.</p>
                <p className='terms-use'>If the party requesting arbitration is represented by counsel, the Request shall also include counsels name, telephone number, mailing address and email address. Counsel must also sign the Request. By signing the Request, counsel certifies to the best of counsels knowledge, information, and belief, formed after an inquiry reasonable under the circumstances, that (1) the Request is not being presented for any improper purpose, such as to harass, cause unnecessary delay, or needlessly increase the cost of dispute resolution; (2) the claims, defenses and other legal contentions are warranted by existing law or by a nonfrivolous argument for extending, modifying, or reversing existing law or for establishing new law; (3) the factual and damages contentions have evidentiary support or, if specifically so identified, will likely have evidentiary support after a reasonable opportunity for further investigation or discovery.</p>
                <p className='terms-use'>The Terms of Use are governed by the laws of the State of California without regard to its conflict of law provisions, except where your jurisdiction states local law prevails. The parties acknowledge that the Terms of Use evidence a transaction involving interstate commerce and that notwithstanding the provision in the preceding sentence with respect to the applicable substantive law, the Federal Arbitration Act, 9 U.S.C. §1 et seq. (FAA) will govern the interpretation and enforcement of this Arbitration Agreement and any arbitration proceedings. If for whatever reason the FAA is inapplicable, the state law governing arbitration agreements in the state in which you reside shall apply.</p>
                <p className='terms-use'>
                  Except as follows, the arbitrator shall have the exclusive authority to resolve any Dispute relating to the interpretation, scope, applicability, enforceability, validity, or formation of this Arbitration Agreement. The exceptions to the preceding sentence are (1) all Disputes arising out of or relating to the Class Action Waiver, including any claim that all or part of the Class Action Waiver is unenforceable, illegal, void or voidable, or such Class Action Waiver has been breached, shall be decided by a court of competent jurisdiction and not by an arbitrator; (2) all Disputes arising out of or relating to the payment of arbitration fees shall be decided only by a court of competent jurisdiction and not by an arbitrator; and (3) all Disputes arising out of or relating to whether either party has satisfied the condition precedent of engaging in the pre-arbitration Informal Dispute Resolution Conference discussed in the “Informal Dispute Resolution” section above, shall be decided only by a court of competent jurisdiction and not by an arbitrator. The parties agree that any and all due dates for arbitration fees shall be suspended, and no action for unpaid fees shall lie, while any Dispute arising out or relating to the Class Action Waiver, the payment of arbitration fees and/or the pre-arbitration Informal Dispute Resolution Conference are being resolved.
                </p>
                <h2 className='text-start fs-3'>Arbitrator</h2>
                <p className='terms-use'>
                  The arbitrator will be either a retired judge or an attorney licensed to practice law in the state of California and will be selected by the parties from the AAAs roster of consumer dispute arbitrators. If the parties are unable to agree upon an arbitrator within thirty-five (35) days of delivery of the Request, then the AAA will appoint the arbitrator in accordance with the AAA Rules, provided that if the Batch Arbitration process is triggered (as described below), the AAA will appoint the arbitrator for each batch.
                </p>
                <h2 className='text-start fs-3'>
                  Arbitration Location and Procedure
                </h2>
                <p className='terms-use'>
                  Unless you and Teachercool otherwise agree, or the Batch Arbitration process is triggered, the arbitration will be conducted in the county where you reside. If your claim does not exceed $10,000 United States dollars, then the arbitration will be conducted solely on the basis of documents you and Teachercool submit to the arbitrator, unless you request a hearing or the arbitrator determines that a hearing is necessary. If your claim exceeds $10,000 United States dollars, your right to a hearing will be determined by the AAA Rules. Subject to the AAA Rules, the arbitrator may direct a reasonable exchange of information by the parties, consistent with the expedited nature of the arbitration. The arbitrator has the authority to grant motions dispositive of all or part of any claims or counterclaims.
                </p>
                <h2 className='text-start fs-3'>
                  Batch Arbitration
                </h2>
                <p className='terms-use'>
                  You agree that any and all Disputes not resolved by the Informal Dispute Resolution Conference process will be finally resolved by arbitration in accordance with the AAA Rules then in effect, except as modified herein. Fees will be assessed based on the AAA Multiple Consumer Case Filings fees then in effect.
                </p>
                <p className='terms-use'>
                  You agree that any and all Disputes not resolved by the Informal Dispute Resolution Conference process will be finally resolved by arbitration in accordance with the AAA Rules then in effect, except as modified herein. Fees will be assessed based on the AAA Multiple Consumer Case Filings fees then in effect.
                </p>
                <p className='terms-use'>To increase the efficiency of administration and resolution of arbitrations, you and Teachercool agree that in the event that there are 100 or more individual Requests of a similar nature filed against Teachercool by or with the assistance of the same law firm, group of law firms or organizations within a 30 day period (or otherwise in close proximity), the AAA (1) will administer the arbitration demands in batches of 100 Requests per batch (plus, to the extent there are less than 100 Requests left over after the batching described above, a final batch consisting of the remaining Requests); (2) appoint one arbitrator for each batch; and (3) provide for the resolution of each batch as a single consolidated arbitration with one set of case management fees and arbitrator compensation due per batch, one procedural calendar, one hearing (if any) in a place to be determined by the arbitrator, and one final award (Batch Arbitration).</p>
                <p>All parties agree that Requests are of a similar nature if they arise out of the same event or factual scenario and raise the same or similar legal issues and seek the same or similar relief. To the extent the parties disagree on the applicability of the Batch Arbitration process, the disagreeing party shall advise the AAA, and the AAA shall appoint a sole standing arbitrator to determine the Batch Arbitration process applicability (Administrative Arbitrator). In an effort to expedite resolution of any such dispute by the Administrative Arbitrator, the parties agree the Administrative Arbitrator may set forth such procedures as are necessary to resolve any disputes promptly. The Administrative Arbitrators fees shall be paid by Teachercool.</p>
                <p className='terms-use'>You and Teachercool agree to cooperate in good faith with the AAA to implement the Batch Arbitration approach including the payment of single case management fees and arbitrator compensation for batches of Requests, as well as any steps to minimize the time and costs of arbitration, which may include: (1) the appointment of a discovery special master to assist the arbitrator in the resolution of discovery disputes; and (2) the adoption of an expedited calendar of the arbitration proceedings.</p>
                <p>This Batch Arbitration provision shall in no way be interpreted as authorizing a class, collective and/or mass arbitration or action of any kind, or arbitration involving joint or consolidated claims under any circumstances, except as set forth in this section.</p>
                <h2 className='text-start fs-3'>
                  Arbitrators Decision
                </h2>
                <p className='terms-use'>
                  The arbitrator will render an award within the time frame specified in the AAA rules. The arbitrators award will include the essential findings and conclusions upon which the arbitrator based the award. Judgment on the arbitration award may be entered in any court having jurisdiction. The arbitrators awarding of damages must be consistent with the terms of the Limitation of Liability section of these Terms of Use as to the types and the amounts of damages for which a party may be held liable. The arbitrator may award declaratory or injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by the partys individual claim.
                </p>
                <p className='terms-use'>If you prevail in arbitration, you may seek an award of reasonable attorneys fees and expenses, to the extent permitted under applicable law. Teachercool will not seek, and hereby waives all rights it may have under applicable law to recover, attorneys fees and expenses if it prevails in arbitration, unless the arbitrator finds that either the substance of your claim or the relief sought in your Request was frivolous or was brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)). The award shall be binding only among the parties and shall have no preclusive effect in any other arbitration or other proceeding involving a different party. The arbitrator may consider, but under no circumstances is the arbitrator bound by, decisions reached in separate arbitrations.</p>
                <h2 className='text-start fs-3'>
                  Fees
                </h2>
                <p className='terms-use'>

                  Your responsibility to pay any AAA filing fees, case management fees and arbitrator compensation will be solely as set forth in the AAA Rules (see Costs of Arbitration). However, if the arbitrator finds that either the substance of your claim or the relief sought in your Request was frivolous or was brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)), Teachercool shall have the right to seek recovery of any AAA filing fees, case management fees and arbitrator compensation it has paid.

                </p>
                <h2 className='text-start fs-3'>
                  Fees
                </h2>
                <p className='terms-use'>

                  Your responsibility to pay any AAA filing fees, case management fees and arbitrator compensation will be solely as set forth in the AAA Rules (see Costs of Arbitration). However, if the arbitrator finds that either the substance of your claim or the relief sought in your Request was frivolous or was brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)), Teachercool shall have the right to seek recovery of any AAA filing fees, case management fees and arbitrator compensation it has paid.

                </p>
                <h2 className='text-start fs-3'>
                  Invalidity, Expiration, and Termination
                </h2>
                <p className='terms-use'>

                  If any part or parts of this Dispute Resolution section are found to be invalid or unenforceable, then such specific part or parts shall be of no force and effect and shall be severed and the remainder of the Dispute Resolution section shall continue in full force and effect to the fullest extent permitted by law. This Dispute Resolution section shall survive any expiration or termination of these Terms of Use or your relationship with Teachercool.

                </p>
                <p className='terms-use'>

                You agree that any Dispute that you have with Teachercool as detailed in this Dispute Resolution section must be initiated via arbitration within the applicable statute of limitation for that claim or controversy, or it will be forever time barred. Likewise, you agree that all applicable statutes of limitation will apply to such arbitration in the same manner as those statutes of limitation would apply in the applicable court of competent jurisdiction.

                </p>
                <h2 className='text-start fs-3'>
                Changes
                </h2>
                <p className='terms-use'>

                Teachercool reserves the right to change the Dispute Resolution, Class Action Waiver, Informal Dispute Resolution, and arbitration sections. If Teachercool changes any such section after the date you first accepted the Terms of Use (or accepted any subsequent changes to the Terms of Use), it will notify you. You agree that your continued use of Services will be deemed acceptance of those changes. If you do not agree to such changes, you may reject any such changes by sending us written notice (including by email to legal) within 30 days of the date such change became effective, as indicated in the Last Updated date. In order to be effective, the notice must include your full name, address, Teachercool username, the email address you currently use to access your Teachercool account and clearly indicate your intent to reject changes to such sections.

                </p>
                <p className='terms-use'>

                You agree that any Dispute that you have with Teachercool as detailed in this Dispute Resolution section must be initiated via arbitration within the applicable statute of limitation for that claim or controversy, or it will be forever time barred. Likewise, you agree that all applicable statutes of limitation will apply to such arbitration in the same manner as those statutes of limitation would apply in the applicable court of competent jurisdiction.

                </p>


              </div>
            </div>
          </div>
        </section>
      </div>
      <Footer />
    </>
  )
}

export default TermsOfUse
